### ISSUE TITLE
Parameterize `RetentionPolicy`

### ISSUE THREAD

**Issue by milesgranger** [aws-samples/aws-lambda-layer-awscli#31]
First, thank you for making this handy Layer available! :100: 

Problem :question: 
---
The template has hard-coded `RetentionPolicy: Retain` 

Proposed Solution: :+1: 
---
Add a `RetentionPolicy` parameter, we can configure when using from SAR.

ie. 
```yaml
LambdaLayerAwsCli:
  Type: AWS::Serverless::Application
  Properties:
    Parameters:
      RetentionPolicy: Delete
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli
      SemanticVersion: 1.18.142
```
